begin;
-- Additive learning features. Prior attempts and lab records are preserved.
alter table public.questions add column if not exists option_explanations jsonb not null default '{}';
alter table public.questions add column if not exists question_kind text not null default 'recall';
alter table public.questions add column if not exists content_key text;
create unique index if not exists questions_content_key_idx on public.questions(content_key) where content_key is not null;

create table if not exists public.lab_drafts (
 user_id uuid not null references auth.users(id) on delete cascade,
 lab_type text not null, exercise_key text not null,
 code text not null check(octet_length(code)<=100000),
 revision integer not null default 1, updated_at timestamptz not null default now(),
 primary key(user_id,lab_type,exercise_key),
 foreign key(lab_type,exercise_key) references public.lab_exercises(lab_type,exercise_key)
);
alter table public.lab_drafts enable row level security;
drop policy if exists "Read own drafts" on public.lab_drafts;
create policy "Read own drafts" on public.lab_drafts for select using(user_id=auth.uid());
create or replace function public.save_lab_draft(p_lab text,p_exercise text,p_code text,p_revision integer)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare d public.lab_drafts;
begin
 if auth.uid() is null or p_revision is null or p_code is null or octet_length(p_code)>100000 then raise exception 'Invalid draft'; end if;
 insert into public.lab_drafts(user_id,lab_type,exercise_key,code) values(auth.uid(),p_lab,p_exercise,p_code)
 on conflict(user_id,lab_type,exercise_key) do update set code=excluded.code,revision=lab_drafts.revision+1,updated_at=now() where lab_drafts.revision=p_revision
 returning * into d;
 if d.user_id is null then raise exception 'Draft changed on another device. Load the cloud version before saving again.'; end if;
 return jsonb_build_object('revision',d.revision,'updated_at',d.updated_at);
end $$;
revoke all on function public.save_lab_draft(text,text,text,integer) from public;
grant execute on function public.save_lab_draft(text,text,text,integer) to authenticated;

create table if not exists public.study_groups (
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id),
 name text not null check(length(name) between 1 and 120),
 join_code text not null unique default replace(gen_random_uuid()::text,'-',''),
 created_at timestamptz not null default now()
);
create table if not exists public.group_members (
 group_id uuid not null references public.study_groups(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 joined_at timestamptz not null default now(), primary key(group_id,user_id)
);
create table if not exists public.study_assignments (
 id uuid primary key default gen_random_uuid(), group_id uuid not null references public.study_groups(id) on delete cascade,
 title text not null check(length(title) between 1 and 160), course_id uuid not null references public.courses(id),
 kind text not null check(kind in ('practice','lab')), lab_type text, exercise_keys text[] not null default '{}',
 due_at timestamptz, created_at timestamptz not null default now(),
 check((kind='practice' and lab_type is null and cardinality(exercise_keys)=0) or (kind='lab' and lab_type is not null and cardinality(exercise_keys) between 1 and 95))
);
alter table public.study_groups enable row level security;
alter table public.group_members enable row level security;
alter table public.study_assignments enable row level security;
-- All classroom access goes through the authenticated API; service credentials never reach the browser.
create table if not exists public.health_events (
 id bigint generated always as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 kind text not null check(kind in ('progress_save','quiz_save','draft_save','engine_timeout','engine_load','tutor_error','page_error')),
 page text not null check(length(page)<=60), created_at timestamptz not null default now()
);
create index if not exists health_events_time_idx on public.health_events(created_at desc);
create index if not exists health_events_user_time_idx on public.health_events(user_id,created_at desc);
alter table public.health_events enable row level security;
create or replace function public.record_health_event(p_kind text,p_page text) returns boolean
language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if auth.uid() is null then return false; end if;
 perform pg_advisory_xact_lock(hashtext(auth.uid()::text));
 if (select count(*) from public.health_events where user_id=auth.uid() and created_at>now()-interval '1 minute')>=10 then return false; end if;
 insert into public.health_events(user_id,kind,page) values(auth.uid(),p_kind,left(p_page,60));
 delete from public.health_events where created_at<now()-interval '7 days';
 return true;
end $$;
revoke all on function public.record_health_event(text,text) from public;
grant execute on function public.record_health_event(text,text) to authenticated;
notify pgrst, 'reload schema';
insert into public.lab_exercises(lab_type,exercise_key,course_code,title,legacy_index) values
('python-lab','project-sales-dashboard','BCIS 313','Project: sales dashboard',30),
('python-lab','project-inventory-planner','BCIS 313','Project: inventory planner',31),
('python-lab','project-customer-invoice','BCIS 313','Project: customer invoice',32)
on conflict(lab_type,exercise_key) do nothing;

-- Applied questions: stable content keys preserve answer history on repeat runs.
insert into public.topics(course_id,name) select id,'arithmetic expression' from public.courses where code='BCIS 313' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A store sells 3 items at SAR 80 each with a 10% discount. Which expression gives the final total?','3 * 80 * 0.90','["3 * 80 * 0.10","3 * (80 - 10)","3 + 80 * 0.90"]'::jsonb,'Apply the discount to the subtotal: 240 × 0.90 = 216.','{"3 * 80 * 0.90":"Apply the discount to the subtotal: 240 × 0.90 = 216.","3 * 80 * 0.10":"This calculates only the discount amount, SAR 24.","3 * (80 - 10)":"This subtracts SAR 10 per item rather than 10%.","3 + 80 * 0.90":"This adds quantity to a price instead of multiplying."}'::jsonb,'application','applied-v1-BCIS-313-1' from public.courses c join public.topics t on t.course_id=c.id and t.name='arithmetic expression' where c.code='BCIS 313' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'for loop' from public.courses where code='BCIS 313' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'What is printed?
total = 0
for sale in [10, 20, 30]:
    total += sale
print(total)','60','["30","0","10"]'::jsonb,'The accumulator adds all three sales: 10 + 20 + 30.','{"0":"The loop updates total on every iteration.","10":"10 includes only the first iteration.","30":"30 is the last sale, not the accumulated total.","60":"The accumulator adds all three sales: 10 + 20 + 30."}'::jsonb,'code','applied-v1-BCIS-313-2' from public.courses c join public.topics t on t.course_id=c.id and t.name='for loop' where c.code='BCIS 313' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'if statement' from public.courses where code='BCIS 313' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A free-delivery rule applies to orders of SAR 200 or more. Which condition correctly includes an order of exactly SAR 200?','total >= 200','["total > 200","total == 200","total <= 200"]'::jsonb,'Greater than or equal includes the boundary and every larger total.','{"total >= 200":"Greater than or equal includes the boundary and every larger total.","total > 200":"This excludes the boundary value 200.","total == 200":"This excludes qualifying totals above 200.","total <= 200":"This includes smaller totals that do not qualify."}'::jsonb,'debugging','applied-v1-BCIS-313-3' from public.courses c join public.topics t on t.course_id=c.id and t.name='if statement' where c.code='BCIS 313' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'dictionary' from public.courses where code='BCIS 313' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'stock = {''pen'': 4}. The key ''book'' might be absent. How can you safely read its stock as zero when absent?','stock.get(''book'', 0)','["stock[''book'']","stock.get(''book'')","stock[0]"]'::jsonb,'dict.get accepts a default value when a key is missing.','{"stock.get(''book'', 0)":"dict.get accepts a default value when a key is missing.","stock[''book'']":"Direct lookup raises KeyError when book is absent.","stock.get(''book'')":"Without a default, get returns None rather than zero.","stock[0]":"0 is treated as a dictionary key, not a position."}'::jsonb,'code','applied-v1-BCIS-313-4' from public.courses c join public.topics t on t.course_id=c.id and t.name='dictionary' where c.code='BCIS 313' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'function' from public.courses where code='BCIS 313' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Why does this function return None?
def revenue(price, quantity):
    price * quantity','It needs return price * quantity','["Multiplication cannot be used in a function","The function must print before returning","The parameters must be global variables"]'::jsonb,'Evaluating an expression alone does not return its value; use return.','{"It needs return price * quantity":"Evaluating an expression alone does not return its value; use return.","Multiplication cannot be used in a function":"Multiplication works normally inside a function.","The function must print before returning":"Printing and returning are independent operations.","The parameters must be global variables":"Parameters provide the needed local values."}'::jsonb,'debugging','applied-v1-BCIS-313-5' from public.courses c join public.topics t on t.course_id=c.id and t.name='function' where c.code='BCIS 313' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'list' from public.courses where code='BCIS 313' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A report must preserve the original sales order. Which code creates a sorted copy?','ordered = sorted(sales)','["ordered = sales.sort()","ordered = sales.reverse()","ordered = sales"]'::jsonb,'sorted returns a new list and leaves sales unchanged.','{"ordered = sorted(sales)":"sorted returns a new list and leaves sales unchanged.","ordered = sales.sort()":"sort mutates sales and returns None.","ordered = sales.reverse()":"reverse mutates sales and does not sort it.","ordered = sales":"This creates another reference to the same unsorted list."}'::jsonb,'application','applied-v1-BCIS-313-6' from public.courses c join public.topics t on t.course_id=c.id and t.name='list' where c.code='BCIS 313' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'JOIN' from public.courses where code='BCIS 311' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Customers(id, name) includes customers with no orders. Which join keeps every customer in the report?','Customers LEFT JOIN Orders ON Customers.id = Orders.customer_id','["Customers INNER JOIN Orders ON Customers.id = Orders.customer_id","Customers CROSS JOIN Orders","Orders LEFT JOIN Customers ON Customers.id = Orders.customer_id"]'::jsonb,'A left join preserves every row from Customers, adding NULLs where no order matches.','{"Customers LEFT JOIN Orders ON Customers.id = Orders.customer_id":"A left join preserves every row from Customers, adding NULLs where no order matches.","Customers INNER JOIN Orders ON Customers.id = Orders.customer_id":"An inner join drops customers with no matching order.","Customers CROSS JOIN Orders":"A cross join produces unrelated combinations.","Orders LEFT JOIN Customers ON Customers.id = Orders.customer_id":"This preserves orders, not customers without orders."}'::jsonb,'application','applied-v1-BCIS-311-1' from public.courses c join public.topics t on t.course_id=c.id and t.name='JOIN' where c.code='BCIS 311' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'WHERE' from public.courses where code='BCIS 311' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Which query finds rows where shipped_at is missing?','SELECT * FROM Orders WHERE shipped_at IS NULL','["SELECT * FROM Orders WHERE shipped_at = NULL","SELECT * FROM Orders WHERE shipped_at = ''''","SELECT * FROM Orders WHERE shipped_at IS NOT NULL"]'::jsonb,'SQL tests for missing values with IS NULL.','{"SELECT * FROM Orders WHERE shipped_at IS NULL":"SQL tests for missing values with IS NULL.","SELECT * FROM Orders WHERE shipped_at = NULL":"Equality with NULL does not evaluate to true.","SELECT * FROM Orders WHERE shipped_at = ''''":"An empty string is not a SQL NULL.","SELECT * FROM Orders WHERE shipped_at IS NOT NULL":"This selects the opposite set: rows with a value."}'::jsonb,'debugging','applied-v1-BCIS-311-2' from public.courses c join public.topics t on t.course_id=c.id and t.name='WHERE' where c.code='BCIS 311' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'GROUP BY' from public.courses where code='BCIS 311' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Which query returns departments whose total salary exceeds 100000?','SELECT department FROM Staff GROUP BY department HAVING SUM(salary) > 100000','["SELECT department FROM Staff WHERE SUM(salary) > 100000 GROUP BY department","SELECT department FROM Staff WHERE salary > 100000","SELECT department FROM Staff ORDER BY salary DESC"]'::jsonb,'HAVING filters aggregated groups after GROUP BY.','{"SELECT department FROM Staff GROUP BY department HAVING SUM(salary) > 100000":"HAVING filters aggregated groups after GROUP BY.","SELECT department FROM Staff WHERE SUM(salary) > 100000 GROUP BY department":"WHERE filters input rows and cannot perform this aggregate-group filter.","SELECT department FROM Staff WHERE salary > 100000":"This checks individual salaries rather than each department total.","SELECT department FROM Staff ORDER BY salary DESC":"Sorting does not filter by an aggregate total."}'::jsonb,'application','applied-v1-BCIS-311-3' from public.courses c join public.topics t on t.course_id=c.id and t.name='GROUP BY' where c.code='BCIS 311' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'foreign key' from public.courses where code='BCIS 311' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'An order refers to customer 999, but no such customer exists. Which constraint should reject it?','Foreign key from Orders.customer_id to Customers.id','["Primary key on Orders.id","NOT NULL on Orders.customer_id","UNIQUE on Orders.total"]'::jsonb,'The foreign key requires the referenced customer to exist.','{"Foreign key from Orders.customer_id to Customers.id":"The foreign key requires the referenced customer to exist.","Primary key on Orders.id":"This prevents duplicate order IDs, not orphan customer references.","NOT NULL on Orders.customer_id":"999 is not NULL, so NOT NULL alone accepts it.","UNIQUE on Orders.total":"Unique totals do not validate customer relationships."}'::jsonb,'application','applied-v1-BCIS-311-4' from public.courses c join public.topics t on t.course_id=c.id and t.name='foreign key' where c.code='BCIS 311' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'UPDATE' from public.courses where code='BCIS 311' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'What is the main error in UPDATE Products SET price = 50 when only product 7 should change?','It needs WHERE id = 7','["UPDATE can change only one row by default","SET must be replaced with SELECT","The table must first be dropped"]'::jsonb,'Without a WHERE condition, every product row is updated.','{"It needs WHERE id = 7":"Without a WHERE condition, every product row is updated.","UPDATE can change only one row by default":"UPDATE affects all qualifying rows, including every row without WHERE.","SET must be replaced with SELECT":"SET is the correct clause for assigning values.","The table must first be dropped":"Dropping the table destroys it and is unrelated to the change."}'::jsonb,'debugging','applied-v1-BCIS-311-5' from public.courses c join public.topics t on t.course_id=c.id and t.name='UPDATE' where c.code='BCIS 311' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'many-to-many relationship' from public.courses where code='BCIS 311' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Each student can take many courses and each course has many students. Which design fits?','Enrollment(student_id, course_id) with foreign keys and a unique pair','["One course_id column in Students","A comma-separated course list in Students","One student_id column in Courses"]'::jsonb,'An enrollment table represents each student-course relationship once.','{"Enrollment(student_id, course_id) with foreign keys and a unique pair":"An enrollment table represents each student-course relationship once.","One course_id column in Students":"A single course_id limits each student to one course.","A comma-separated course list in Students":"A comma-separated list makes constraints and joins difficult.","One student_id column in Courses":"A single student_id limits a course to one student."}'::jsonb,'application','applied-v1-BCIS-311-6' from public.courses c join public.topics t on t.course_id=c.id and t.name='many-to-many relationship' where c.code='BCIS 311' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'semantic HTML' from public.courses where code='BCIS 317' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A control submits a form. Which HTML element provides native button keyboard behavior?','<button type="submit">Save</button>','["<div onclick=\"save()\">Save</div>","<span>Save</span>","<h2>Save</h2>"]'::jsonb,'A native button supports focus, keyboard activation and form semantics.','{"<button type=\"submit\">Save</button>":"A native button supports focus, keyboard activation and form semantics.","<div onclick=\"save()\">Save</div>":"A clickable div needs additional keyboard and accessibility handling.","<span>Save</span>":"A span has no built-in action.","<h2>Save</h2>":"A heading describes a section rather than an action."}'::jsonb,'application','applied-v1-BCIS-317-1' from public.courses c join public.topics t on t.course_id=c.id and t.name='semantic HTML' where c.code='BCIS 317' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'CSS box model' from public.courses where code='BCIS 317' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'With content-box sizing, width:200px, padding:10px and border:2px solid, what is the total horizontal border-box width?','224px','["200px","212px","220px"]'::jsonb,'Add left and right padding (20px) and borders (4px) to 200px.','{"224px":"Add left and right padding (20px) and borders (4px) to 200px.","200px":"200px is only the content width under content-box sizing.","212px":"Both sides must be counted, not one.","220px":"220px includes padding but omits the borders."}'::jsonb,'application','applied-v1-BCIS-317-2' from public.courses c join public.topics t on t.course_id=c.id and t.name='CSS box model' where c.code='BCIS 317' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'DOM' from public.courses where code='BCIS 317' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A customer name comes from a text field. Which assignment displays it as text without interpreting HTML?','element.textContent = name','["element.innerHTML = name","document.write(name)","eval(name)"]'::jsonb,'textContent inserts literal text instead of parsing markup.','{"element.textContent = name":"textContent inserts literal text instead of parsing markup.","element.innerHTML = name":"innerHTML parses markup and can introduce injection risks.","document.write(name)":"document.write parses HTML and can replace the document.","eval(name)":"eval executes JavaScript rather than displaying plain text."}'::jsonb,'code','applied-v1-BCIS-317-3' from public.courses c join public.topics t on t.course_id=c.id and t.name='DOM' where c.code='BCIS 317' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'responsive design' from public.courses where code='BCIS 317' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Which rule applies only when the viewport is at most 600px wide?','@media (max-width: 600px) { .grid { grid-template-columns: 1fr; } }','["@media (min-width: 600px) { .grid { grid-template-columns: 1fr; } }",".grid { width: 600px; }","@media print { .grid { display: none; } }"]'::jsonb,'max-width matches viewports at or below the specified width.','{"@media (max-width: 600px) { .grid { grid-template-columns: 1fr; } }":"max-width matches viewports at or below the specified width.","@media (min-width: 600px) { .grid { grid-template-columns: 1fr; } }":"min-width matches the opposite range.",".grid { width: 600px; }":"A fixed element width does not conditionally match the viewport.","@media print { .grid { display: none; } }":"The print media query targets printing rather than narrow screens."}'::jsonb,'application','applied-v1-BCIS-317-4' from public.courses c join public.topics t on t.course_id=c.id and t.name='responsive design' where c.code='BCIS 317' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'JavaScript' from public.courses where code='BCIS 317' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'What does this expression evaluate to?
''5'' + 2','''52''','["7","''7''","10"]'::jsonb,'With a string operand, + performs string concatenation here.','{"7":"Numeric addition would require converting ''5'' to a number.","10":"No multiplication is performed.","''52''":"With a string operand, + performs string concatenation here.","''7''":"Concatenation joins the original values; it does not add them first."}'::jsonb,'code','applied-v1-BCIS-317-5' from public.courses c join public.topics t on t.course_id=c.id and t.name='JavaScript' where c.code='BCIS 317' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'accessibility' from public.courses where code='BCIS 317' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A form input has id="email". Which label association is correct?','<label for="email">Email</label>','["<label for=\"name\">Email</label>","<p>Email</p>","<label id=\"email\">Email</label>"]'::jsonb,'The label''s for attribute must match the input''s id.','{"<label for=\"email\">Email</label>":"The label''s for attribute must match the input''s id.","<label for=\"name\">Email</label>":"The for value points to a different input ID.","<p>Email</p>":"Nearby paragraph text does not programmatically label the input.","<label id=\"email\">Email</label>":"A label id does not associate it with the input."}'::jsonb,'application','applied-v1-BCIS-317-6' from public.courses c join public.topics t on t.course_id=c.id and t.name='accessibility' where c.code='BCIS 317' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'shared database' from public.courses where code='BCIS 324' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Sales accepts an order using yesterday''s stock export. Warehouse reports that the item has sold out. What best addresses the information gap?','Use a shared, timely inventory record across sales and warehouse','["Create separate stock spreadsheets for each salesperson","Refresh stock once at year end","Remove inventory checks"]'::jsonb,'Shared inventory visibility reduces decisions based on inconsistent stock copies.','{"Use a shared, timely inventory record across sales and warehouse":"Shared inventory visibility reduces decisions based on inconsistent stock copies.","Create separate stock spreadsheets for each salesperson":"More separate copies increase inconsistency.","Refresh stock once at year end":"An annual refresh cannot support current availability decisions.","Remove inventory checks":"Removing checks hides shortages rather than addressing them."}'::jsonb,'application','applied-v1-BCIS-324-1' from public.courses c join public.topics t on t.course_id=c.id and t.name='shared database' where c.code='BCIS 324' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'procure-to-pay' from public.courses where code='BCIS 324' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'An invoice arrives for 100 units, but only 80 were received. What should the team do before payment?','Investigate the mismatch between purchase order, receipt and invoice','["Pay the invoice without checking","Change the receipt to 100 without evidence","Delete the purchase order"]'::jsonb,'Matching the documents identifies discrepancies that need resolution before payment.','{"Investigate the mismatch between purchase order, receipt and invoice":"Matching the documents identifies discrepancies that need resolution before payment.","Pay the invoice without checking":"Payment without verification may pay for undelivered goods.","Change the receipt to 100 without evidence":"Changing records without evidence hides the discrepancy.","Delete the purchase order":"Deleting the order removes needed evidence."}'::jsonb,'application','applied-v1-BCIS-324-2' from public.courses c join public.topics t on t.course_id=c.id and t.name='procure-to-pay' where c.code='BCIS 324' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'master data' from public.courses where code='BCIS 324' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Two departments created different IDs for the same supplier. What is the strongest corrective action?','Reconcile duplicate supplier records and define an owner for master data','["Keep duplicates and rely on memory","Create a third supplier ID","Disable supplier reporting"]'::jsonb,'Reconciliation plus ownership addresses both the existing duplicate and its recurrence.','{"Reconcile duplicate supplier records and define an owner for master data":"Reconciliation plus ownership addresses both the existing duplicate and its recurrence.","Keep duplicates and rely on memory":"Memory is not a reliable control across departments.","Create a third supplier ID":"Another ID adds further duplication.","Disable supplier reporting":"Removing reports does not repair the underlying records."}'::jsonb,'application','applied-v1-BCIS-324-3' from public.courses c join public.topics t on t.course_id=c.id and t.name='master data' where c.code='BCIS 324' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'change management' from public.courses where code='BCIS 324' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A new ERP workflow is correct, but staff continue using spreadsheets. Which response best supports adoption?','Provide role-based training, explain the workflow and gather user feedback','["Assume installation alone guarantees adoption","Add more mandatory fields without explanation","Stop all communication about the system"]'::jsonb,'Adoption depends on understanding, practical training and addressing user concerns.','{"Provide role-based training, explain the workflow and gather user feedback":"Adoption depends on understanding, practical training and addressing user concerns.","Assume installation alone guarantees adoption":"Technical installation does not ensure changed working habits.","Add more mandatory fields without explanation":"Unexplained friction may further discourage use.","Stop all communication about the system":"Less communication makes the transition harder."}'::jsonb,'application','applied-v1-BCIS-324-4' from public.courses c join public.topics t on t.course_id=c.id and t.name='change management' where c.code='BCIS 324' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'segregation of duties' from public.courses where code='BCIS 324' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'One employee creates a supplier, approves its invoices and releases payment. Which change reduces control risk?','Separate supplier maintenance, invoice approval and payment authorization','["Give the employee a second account","Hide the payment log","Remove approval limits"]'::jsonb,'Independent roles reduce the opportunity for one person to authorize an entire improper transaction.','{"Separate supplier maintenance, invoice approval and payment authorization":"Independent roles reduce the opportunity for one person to authorize an entire improper transaction.","Give the employee a second account":"Two accounts held by one person do not create independent review.","Hide the payment log":"Hiding logs reduces accountability.","Remove approval limits":"Removing limits weakens rather than strengthens control."}'::jsonb,'application','applied-v1-BCIS-324-5' from public.courses c join public.topics t on t.course_id=c.id and t.name='segregation of duties' where c.code='BCIS 324' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'implementation' from public.courses where code='BCIS 324' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'An ERP cutover is tomorrow and opening balances have not been reconciled. What is the best next step?','Resolve and verify balance differences before approving cutover','["Approve cutover because the date is fixed","Delete the old balances","Let users discover discrepancies later"]'::jsonb,'Reliable opening balances are necessary for a controlled transition.','{"Resolve and verify balance differences before approving cutover":"Reliable opening balances are necessary for a controlled transition.","Approve cutover because the date is fixed":"A schedule does not establish data correctness.","Delete the old balances":"Deleting source balances prevents reconciliation.","Let users discover discrepancies later":"Unverified balances shift preventable errors into operations."}'::jsonb,'application','applied-v1-BCIS-324-6' from public.courses c join public.topics t on t.course_id=c.id and t.name='implementation' where c.code='BCIS 324' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'KPI' from public.courses where code='BCIS 411' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A support team wants to reduce resolution delays. Which metric most directly measures that objective?','Median time from ticket creation to resolution','["Number of dashboard colors","Total number of employees","Number of charts published"]'::jsonb,'Elapsed resolution time measures the delay the team wants to reduce.','{"Median time from ticket creation to resolution":"Elapsed resolution time measures the delay the team wants to reduce.","Number of dashboard colors":"Visual styling does not measure resolution delay.","Total number of employees":"Headcount may influence capacity but is not the delay itself.","Number of charts published":"Chart production measures reporting activity, not support outcomes."}'::jsonb,'application','applied-v1-BCIS-411-1' from public.courses c join public.topics t on t.course_id=c.id and t.name='KPI' where c.code='BCIS 411' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'data visualization' from public.courses where code='BCIS 411' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A dashboard compares sales across five regions. Which chart makes their magnitudes easy to compare?','Bar chart with a common zero baseline','["A separate pie chart for each region","A 3D decorative sphere","A line chart with regions randomly reordered every day"]'::jsonb,'Bars sharing a baseline make category magnitudes straightforward to compare.','{"Bar chart with a common zero baseline":"Bars sharing a baseline make category magnitudes straightforward to compare.","A separate pie chart for each region":"Separate pies lack a common comparable scale.","A 3D decorative sphere":"Decoration does not encode the comparison clearly.","A line chart with regions randomly reordered every day":"Random category order makes comparison unstable and lines imply sequence."}'::jsonb,'application','applied-v1-BCIS-411-2' from public.courses c join public.topics t on t.course_id=c.id and t.name='data visualization' where c.code='BCIS 411' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'data warehouse' from public.courses where code='BCIS 411' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Sales revenue is counted twice after joining orders to order lines. What should be checked first?','The grain of each table and whether order totals repeat per line','["The dashboard background color","The number of user passwords","The screen brightness"]'::jsonb,'An order-level total repeated across line-level rows is double-counted when summed.','{"The grain of each table and whether order totals repeat per line":"An order-level total repeated across line-level rows is double-counted when summed.","The dashboard background color":"Appearance does not alter aggregation grain.","The number of user passwords":"Passwords do not explain duplicated revenue rows.","The screen brightness":"Screen settings do not change the data calculation."}'::jsonb,'debugging','applied-v1-BCIS-411-3' from public.courses c join public.topics t on t.course_id=c.id and t.name='data warehouse' where c.code='BCIS 411' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'ETL' from public.courses where code='BCIS 411' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A source changes date formatting from DD/MM/YYYY to MM/DD/YYYY. What should a pipeline do?','Validate and explicitly parse the expected source date format','["Treat every date as plain text forever","Silently guess each date format","Drop all dates without reporting it"]'::jsonb,'Explicit parsing and validation prevent ambiguous dates from being silently misinterpreted.','{"Validate and explicitly parse the expected source date format":"Explicit parsing and validation prevent ambiguous dates from being silently misinterpreted.","Treat every date as plain text forever":"Plain text prevents reliable date operations and leaves ambiguity unresolved.","Silently guess each date format":"Guessing can swap month and day without detection.","Drop all dates without reporting it":"Silent removal loses information and hides the issue."}'::jsonb,'application','applied-v1-BCIS-411-4' from public.courses c join public.topics t on t.course_id=c.id and t.name='ETL' where c.code='BCIS 411' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'dashboard' from public.courses where code='BCIS 411' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A KPI reports 120% of target. Actual sales are 600. What was the target?','500','["720","120","600"]'::jsonb,'Actual ÷ target = 1.2, so target = 600 ÷ 1.2 = 500.','{"120":"120 is the percentage number, not the monetary target.","500":"Actual ÷ target = 1.2, so target = 600 ÷ 1.2 = 500.","600":"A target of 600 would yield 100%.","720":"720 multiplies actual by 1.2 instead of solving for the target."}'::jsonb,'application','applied-v1-BCIS-411-5' from public.courses c join public.topics t on t.course_id=c.id and t.name='dashboard' where c.code='BCIS 411' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'data quality' from public.courses where code='BCIS 411' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Two reports show different monthly totals because one includes cancelled orders. What should be agreed first?','A shared business definition of included revenue transactions','["Which report has the nicer layout","A random adjustment to make totals equal","A policy to stop comparing reports"]'::jsonb,'Consistent inclusion rules are needed before two totals can be meaningfully compared.','{"A shared business definition of included revenue transactions":"Consistent inclusion rules are needed before two totals can be meaningfully compared.","Which report has the nicer layout":"Layout does not resolve different business definitions.","A random adjustment to make totals equal":"An arbitrary adjustment conceals the reason for the difference.","A policy to stop comparing reports":"Avoiding comparison leaves the inconsistency unresolved."}'::jsonb,'application','applied-v1-BCIS-411-6' from public.courses c join public.topics t on t.course_id=c.id and t.name='data quality' where c.code='BCIS 411' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'mean' from public.courses where code='BCIS 421' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Sales values are 10, 10, 10 and 90. What is their mean?','30','["10","90","120"]'::jsonb,'The total is 120; divide by four observations to obtain 30.','{"10":"10 is the median and mode here, not the mean.","30":"The total is 120; divide by four observations to obtain 30.","90":"90 is the maximum. It does not answer the requested calculation.","120":"120 is the sum before division."}'::jsonb,'application','applied-v1-BCIS-421-1' from public.courses c join public.topics t on t.course_id=c.id and t.name='mean' where c.code='BCIS 421' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'median' from public.courses where code='BCIS 421' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'For delivery times 2, 3, 3, 4 and 100 days, which summary is less distorted by the extreme delay?','Median: 3 days','["Mean: 22.4 days","Maximum: 100 days","Sum: 112 days"]'::jsonb,'The median is the middle ordered value and is less sensitive to one extreme value.','{"Median: 3 days":"The median is the middle ordered value and is less sensitive to one extreme value.","Mean: 22.4 days":"The extreme delay pulls the mean well above most observations.","Maximum: 100 days":"The maximum describes only the most extreme case.","Sum: 112 days":"The sum is not a typical per-delivery duration."}'::jsonb,'application','applied-v1-BCIS-421-2' from public.courses c join public.topics t on t.course_id=c.id and t.name='median' where c.code='BCIS 421' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'test set' from public.courses where code='BCIS 421' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A model''s settings were repeatedly chosen based on test-set scores. What is the problem?','The test set influenced development and no longer provides an untouched final evaluation','["Test data must always train the model","More test-set tuning guarantees generalization","A high test score proves causation"]'::jsonb,'Repeated tuning against the test set leaks evaluation information into development.','{"The test set influenced development and no longer provides an untouched final evaluation":"Repeated tuning against the test set leaks evaluation information into development.","Test data must always train the model":"Training on test data defeats its independent evaluation role.","More test-set tuning guarantees generalization":"Repeated tuning can overfit the test set.","A high test score proves causation":"Predictive performance does not establish a causal relationship."}'::jsonb,'application','applied-v1-BCIS-421-3' from public.courses c join public.topics t on t.course_id=c.id and t.name='test set' where c.code='BCIS 421' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'classification' from public.courses where code='BCIS 421' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Only 1% of transactions are fraud. A model predicts every transaction as non-fraud. Which statement is correct?','It has 99% accuracy but detects none of the fraud cases','["It detects 99% of fraud","Its accuracy is 1%","It has perfect fraud recall"]'::jsonb,'The majority class creates high accuracy, while fraud recall is zero.','{"It has 99% accuracy but detects none of the fraud cases":"The majority class creates high accuracy, while fraud recall is zero.","It detects 99% of fraud":"Overall accuracy is not the same as fraud detection rate.","Its accuracy is 1%":"It correctly predicts the 99% non-fraud majority.","It has perfect fraud recall":"It misses every fraud case, so recall is zero."}'::jsonb,'application','applied-v1-BCIS-421-4' from public.courses c join public.topics t on t.course_id=c.id and t.name='classification' where c.code='BCIS 421' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'overfitting' from public.courses where code='BCIS 421' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'A model achieves 99% training accuracy and 62% validation accuracy. What is a reasonable concern?','It may be overfitting the training data','["It must generalize perfectly","Validation accuracy should be ignored","The validation labels should be replaced with model predictions"]'::jsonb,'A large training-validation gap suggests the model may have learned training-specific patterns.','{"It may be overfitting the training data":"A large training-validation gap suggests the model may have learned training-specific patterns.","It must generalize perfectly":"The validation result contradicts perfect generalization.","Validation accuracy should be ignored":"Validation performance helps assess unseen-data behavior.","The validation labels should be replaced with model predictions":"Replacing labels would invalidate evaluation."}'::jsonb,'application','applied-v1-BCIS-421-5' from public.courses c join public.topics t on t.course_id=c.id and t.name='overfitting' where c.code='BCIS 421' on conflict(content_key) where content_key is not null do nothing;
insert into public.topics(course_id,name) select id,'missing values' from public.courses where code='BCIS 421' on conflict(course_id,name) do nothing;
insert into public.questions(course_id,topic_id,question,correct_answer,wrong_answers,explanation,option_explanations,question_kind,content_key) select c.id,t.id,'Income is missing for 20% of rows. Why is replacing every missing value with zero risky?','Zero income is a real value and can bias the analysis if missingness means unknown','["Zero is always the correct imputation","Missing values are necessarily fraudulent","Replacing values cannot affect a mean"]'::jsonb,'Choose a justified missing-data strategy; unknown income is not automatically zero income.','{"Zero income is a real value and can bias the analysis if missingness means unknown":"Choose a justified missing-data strategy; unknown income is not automatically zero income.","Zero is always the correct imputation":"The appropriate strategy depends on context and the missingness mechanism.","Missing values are necessarily fraudulent":"Missingness alone does not establish fraud.","Replacing values cannot affect a mean":"Adding zeros changes both summaries and model inputs."}'::jsonb,'application','applied-v1-BCIS-421-6' from public.courses c join public.topics t on t.course_id=c.id and t.name='missing values' where c.code='BCIS 421' on conflict(content_key) where content_key is not null do nothing;

notify pgrst, 'reload schema';
commit;
