// Exercise IDs travel with their definitions. Never change an existing ID.
window.LAB_CONTENT = {
  "python-lab": [
    Object.assign(
      [
        "Basics",
        "Beginner",
        "Print a message",
        "Print exactly: Hello, tamareen!",
        "Hello, tamareen!",
        "# write code\n",
        [["out", "Hello, tamareen!"]],
      ],
      { id: "print-a-message", legacyIndex: 0 },
    ),
    Object.assign(
      [
        "Basics",
        "Beginner",
        "Arithmetic total",
        "Set price=80 and quantity=3, then print their product.",
        "240",
        "price=80\nquantity=3\n",
        [["out", "240"]],
      ],
      { id: "arithmetic-total", legacyIndex: 1 },
    ),
    Object.assign(
      [
        "Basics",
        "Beginner",
        "Calculate VAT",
        "Define total_with_vat(price) that returns price plus 15% VAT.",
        "total_with_vat(100) → 115",
        "def total_with_vat(price):\n    pass",
        [
          ["expr", "total_with_vat(100)", 115],
          ["expr", "total_with_vat(200)", 230],
        ],
      ],
      { id: "calculate-vat", legacyIndex: 2 },
    ),
    Object.assign(
      [
        "Basics",
        "Beginner",
        "Convert minutes",
        "Define hours(minutes) that converts minutes to hours.",
        "hours(90) → 1.5",
        "def hours(minutes):\n    pass",
        [
          ["expr", "hours(90)", 1.5],
          ["expr", "hours(120)", 2],
        ],
      ],
      { id: "convert-minutes", legacyIndex: 3 },
    ),
    Object.assign(
      [
        "Conditions",
        "Beginner",
        "Positive or negative",
        "Define sign(n) returning Positive, Negative, or Zero.",
        "sign(-4) → Negative",
        "def sign(n):\n    pass",
        [
          ["expr", "sign(-4)", "Negative"],
          ["expr", "sign(0)", "Zero"],
          ["expr", "sign(8)", "Positive"],
        ],
      ],
      { id: "positive-or-negative", legacyIndex: 4 },
    ),
    Object.assign(
      [
        "Conditions",
        "Beginner",
        "Pass or fail",
        "Define result(mark) returning Pass for marks >= 60, otherwise Fail.",
        "result(75) → Pass",
        "def result(mark):\n    pass",
        [
          ["expr", "result(75)", "Pass"],
          ["expr", "result(59)", "Fail"],
          ["expr", "result(60)", "Pass"],
        ],
      ],
      { id: "pass-or-fail", legacyIndex: 5 },
    ),
    Object.assign(
      [
        "Conditions",
        "Intermediate",
        "Discount rule",
        "Define discount(total): return 0.10*total if total >= 500, otherwise 0.",
        "discount(600) → 60",
        "def discount(total):\n    pass",
        [
          ["expr", "discount(600)", 60],
          ["expr", "discount(499)", 0],
        ],
      ],
      { id: "discount-rule", legacyIndex: 6 },
    ),
    Object.assign(
      [
        "Conditions",
        "Intermediate",
        "Largest of three",
        "Define largest(a,b,c) returning the largest value.",
        "largest(3,9,5) → 9",
        "def largest(a,b,c):\n    pass",
        [
          ["expr", "largest(3,9,5)", 9],
          ["expr", "largest(-1,-5,-2)", -1],
        ],
      ],
      { id: "largest-of-three", legacyIndex: 7 },
    ),
    Object.assign(
      [
        "Loops",
        "Beginner",
        "Count 1 to 5",
        "Use a loop to print 1 through 5, one per line.",
        "1\n2\n3\n4\n5",
        "# use a loop\n",
        [["out", "1\n2\n3\n4\n5"]],
      ],
      { id: "count-1-to-5", legacyIndex: 8 },
    ),
    Object.assign(
      [
        "Loops",
        "Beginner",
        "Sum 1 to 10",
        "Use a loop to calculate and print the sum 1 through 10.",
        "55",
        "total=0\n",
        [["out", "55"]],
      ],
      { id: "sum-1-to-10", legacyIndex: 9 },
    ),
    Object.assign(
      [
        "Loops",
        "Intermediate",
        "Even numbers",
        "Define evens(n) returning a list of even numbers from 1 through n.",
        "evens(8) → [2,4,6,8]",
        "def evens(n):\n    pass",
        [
          ["expr", "evens(8)", [2, 4, 6, 8]],
          ["expr", "evens(5)", [2, 4]],
        ],
      ],
      { id: "even-numbers", legacyIndex: 10 },
    ),
    Object.assign(
      [
        "Loops",
        "Intermediate",
        "Factorial",
        "Define factorial(n) using iteration.",
        "factorial(5) → 120",
        "def factorial(n):\n    pass",
        [
          ["expr", "factorial(5)", 120],
          ["expr", "factorial(0)", 1],
        ],
      ],
      { id: "factorial", legacyIndex: 11 },
    ),
    Object.assign(
      [
        "Functions",
        "Beginner",
        "Revenue",
        "Define revenue(price,quantity).",
        "revenue(25,4) → 100",
        "def revenue(price,quantity):\n    pass",
        [
          ["expr", "revenue(25,4)", 100],
          ["expr", "revenue(12.5,2)", 25],
        ],
      ],
      { id: "revenue", legacyIndex: 12 },
    ),
    Object.assign(
      [
        "Functions",
        "Beginner",
        "Profit",
        "Define profit(revenue,cost) returning revenue minus cost.",
        "profit(900,650) → 250",
        "def profit(revenue,cost):\n    pass",
        [
          ["expr", "profit(900,650)", 250],
          ["expr", "profit(100,120)", -20],
        ],
      ],
      { id: "profit", legacyIndex: 13 },
    ),
    Object.assign(
      [
        "Functions",
        "Intermediate",
        "Commission",
        "Define commission(sales,rate=0.05) returning sales × rate.",
        "commission(1000) → 50",
        "def commission(sales,rate=0.05):\n    pass",
        [
          ["expr", "commission(1000)", 50],
          ["expr", "commission(1000,0.1)", 100],
        ],
      ],
      { id: "commission", legacyIndex: 14 },
    ),
    Object.assign(
      [
        "Strings",
        "Beginner",
        "Clean customer name",
        "Strip outer spaces and convert a name to title case.",
        'clean_name("  sara ali ") → Sara Ali',
        "def clean_name(name):\n    pass",
        [
          ["expr", 'clean_name("  sara ali ")', "Sara Ali"],
          ["expr", 'clean_name("MOHAMMAD")', "Mohammad"],
        ],
      ],
      { id: "clean-customer-name", legacyIndex: 15 },
    ),
    Object.assign(
      [
        "Strings",
        "Beginner",
        "Email domain",
        "Define domain(email) returning the part after @.",
        'domain("a@example.com") → example.com',
        "def domain(email):\n    pass",
        [
          ["expr", 'domain("a@example.com")', "example.com"],
          ["expr", 'domain("x@tamareen.online")', "tamareen.online"],
        ],
      ],
      { id: "email-domain", legacyIndex: 16 },
    ),
    Object.assign(
      [
        "Strings",
        "Intermediate",
        "Count words",
        "Define word_count(text) returning number of whitespace-separated words.",
        'word_count("data is useful") → 3',
        "def word_count(text):\n    pass",
        [
          ["expr", 'word_count("data is useful")', 3],
          ["expr", 'word_count("  hello world  ")', 2],
        ],
      ],
      { id: "count-words", legacyIndex: 17 },
    ),
    Object.assign(
      [
        "Strings",
        "Intermediate",
        "Mask account",
        "Define mask(value) keeping only the last 4 characters and replacing earlier characters with *.",
        'mask("12345678") → ****5678',
        "def mask(value):\n    pass",
        [
          ["expr", 'mask("12345678")', "****5678"],
          ["expr", 'mask("ABCDEF")', "**CDEF"],
        ],
      ],
      { id: "mask-account", legacyIndex: 18 },
    ),
    Object.assign(
      [
        "Lists",
        "Beginner",
        "Average sales",
        "Return the arithmetic mean of a list.",
        "average_sales([100,200,300]) → 200",
        "def average_sales(sales):\n    pass",
        [
          ["expr", "average_sales([100,200,300])", 200],
          ["expr", "average_sales([10,20])", 15],
        ],
      ],
      { id: "average-sales", legacyIndex: 19 },
    ),
    Object.assign(
      [
        "Lists",
        "Beginner",
        "Highest sale",
        "Return the largest value in sales.",
        "highest([40,90,20]) → 90",
        "def highest(sales):\n    pass",
        [
          ["expr", "highest([40,90,20])", 90],
          ["expr", "highest([-2,-8])", -2],
        ],
      ],
      { id: "highest-sale", legacyIndex: 20 },
    ),
    Object.assign(
      [
        "Lists",
        "Intermediate",
        "Above target",
        "Return values greater than target.",
        "above_target([20,80,50],50) → [80]",
        "def above_target(values,target):\n    pass",
        [
          ["expr", "above_target([20,80,50],50)", [80]],
          ["expr", "above_target([1,2,3],1)", [2, 3]],
        ],
      ],
      { id: "above-target", legacyIndex: 21 },
    ),
    Object.assign(
      [
        "Lists",
        "Intermediate",
        "Remove duplicates",
        "Return unique values while preserving original order.",
        "unique([1,2,1,3]) → [1,2,3]",
        "def unique(values):\n    pass",
        [
          ["expr", "unique([1,2,1,3])", [1, 2, 3]],
          ["expr", 'unique(["a","a","b"])', ["a", "b"]],
        ],
      ],
      { id: "remove-duplicates", legacyIndex: 22 },
    ),
    Object.assign(
      [
        "Dictionaries",
        "Beginner",
        "Order total",
        "Multiply price by quantity from a dictionary.",
        'order_total({"price":20,"quantity":3}) → 60',
        "def order_total(order):\n    pass",
        [
          ["expr", 'order_total({"price":20,"quantity":3})', 60],
          ["expr", 'order_total({"price":7.5,"quantity":4})', 30],
        ],
      ],
      { id: "order-total", legacyIndex: 23 },
    ),
    Object.assign(
      [
        "Dictionaries",
        "Intermediate",
        "Inventory value",
        "Given {product: {price,qty}}, return total inventory value.",
        'inventory_value({"A":{"price":10,"qty":2}}) → 20',
        "def inventory_value(items):\n    pass",
        [
          ["expr", 'inventory_value({"A":{"price":10,"qty":2}})', 20],
          [
            "expr",
            'inventory_value({"A":{"price":5,"qty":2},"B":{"price":3,"qty":4}})',
            22,
          ],
        ],
      ],
      { id: "inventory-value", legacyIndex: 24 },
    ),
    Object.assign(
      [
        "Dictionaries",
        "Intermediate",
        "Top seller",
        "Given {name:sales}, return the name with highest sales.",
        'top_seller({"A":20,"B":50}) → B',
        "def top_seller(data):\n    pass",
        [
          ["expr", 'top_seller({"A":20,"B":50})', "B"],
          ["expr", 'top_seller({"Sara":90,"Ali":70})', "Sara"],
        ],
      ],
      { id: "top-seller", legacyIndex: 25 },
    ),
    Object.assign(
      [
        "Mixed",
        "Intermediate",
        "Sales summary",
        "Return a dictionary with total and average for a sales list.",
        'summary([10,20,30]) → {"total":60,"average":20}',
        "def summary(sales):\n    pass",
        [
          ["expr", "summary([10,20,30])", { total: 60, average: 20 }],
          ["expr", "summary([5,15])", { total: 20, average: 10 }],
        ],
      ],
      { id: "sales-summary", legacyIndex: 26 },
    ),
    Object.assign(
      [
        "Mixed",
        "Advanced",
        "Frequency table",
        "Return a dictionary counting each value in a list.",
        'frequency(["A","B","A"]) → {"A":2,"B":1}',
        "def frequency(values):\n    pass",
        [
          ["expr", 'frequency(["A","B","A"])', { A: 2, B: 1 }],
          ["expr", "frequency([1,1,2,3,3,3])", { 1: 2, 2: 1, 3: 3 }],
        ],
      ],
      { id: "frequency-table", legacyIndex: 27 },
    ),
    Object.assign(
      [
        "Mixed",
        "Advanced",
        "Customer spend",
        "Given a list of (customer,amount) tuples, aggregate total spend by customer.",
        'spend([("A",10),("A",5),("B",7)]) → {"A":15,"B":7}',
        "def spend(rows):\n    pass",
        [
          ["expr", 'spend([("A",10),("A",5),("B",7)])', { A: 15, B: 7 }],
          [
            "expr",
            'spend([("Sara",20),("Ali",10),("Sara",30)])',
            { Sara: 50, Ali: 10 },
          ],
        ],
      ],
      { id: "customer-spend", legacyIndex: 28 },
    ),
    Object.assign(
      [
        "Mixed",
        "Advanced",
        "Moving average",
        "Return averages of each consecutive window of size k.",
        "moving_average([1,2,3,4],2) → [1.5,2.5,3.5]",
        "def moving_average(values,k):\n    pass",
        [
          ["expr", "moving_average([1,2,3,4],2)", [1.5, 2.5, 3.5]],
          ["expr", "moving_average([10,20,30],3)", [20]],
        ],
      ],
      { id: "moving-average", legacyIndex: 29 },
    ),
  ],
  "sql-lab": [
    Object.assign(
      [
        "SELECT",
        "Beginner",
        "All customers",
        "Return every column and row from Customers.",
        "SELECT * FROM Customers",
        "SELECT *\nFROM Customers;",
      ],
      { id: "all-customers", legacyIndex: 0 },
    ),
    Object.assign(
      [
        "SELECT",
        "Beginner",
        "Customer names",
        "Return only Name from Customers ordered alphabetically.",
        "SELECT Name FROM Customers ORDER BY Name",
        "SELECT Name\nFROM Customers\nORDER BY Name;",
      ],
      { id: "customer-names", legacyIndex: 1 },
    ),
    Object.assign(
      [
        "SELECT",
        "Beginner",
        "Product catalog",
        "Return ProductName and Price ordered by ProductName.",
        "SELECT ProductName,Price FROM Products ORDER BY ProductName",
        "SELECT ProductName, Price\nFROM Products\nORDER BY ProductName;",
      ],
      { id: "product-catalog", legacyIndex: 2 },
    ),
    Object.assign(
      [
        "WHERE",
        "Beginner",
        "Jeddah customers",
        "Return Name for customers in Jeddah, ordered by Name.",
        "SELECT Name FROM Customers WHERE City='Jeddah' ORDER BY Name",
        "SELECT Name FROM Customers\nWHERE City='Jeddah'\nORDER BY Name;",
      ],
      { id: "jeddah-customers", legacyIndex: 3 },
    ),
    Object.assign(
      [
        "WHERE",
        "Beginner",
        "Expensive products",
        "Return ProductName and Price where Price > 100, highest first.",
        "SELECT ProductName,Price FROM Products WHERE Price>100 ORDER BY Price DESC",
        "SELECT ProductName, Price FROM Products\nWHERE Price > 100\nORDER BY Price DESC;",
      ],
      { id: "expensive-products", legacyIndex: 4 },
    ),
    Object.assign(
      [
        "WHERE",
        "Intermediate",
        "Price range",
        "Return ProductName and Price where Price is between 75 and 200 inclusive, ordered by Price.",
        "SELECT ProductName,Price FROM Products WHERE Price BETWEEN 75 AND 200 ORDER BY Price",
        "SELECT ProductName, Price FROM Products\nWHERE Price BETWEEN 75 AND 200\nORDER BY Price;",
      ],
      { id: "price-range", legacyIndex: 5 },
    ),
    Object.assign(
      [
        "WHERE",
        "Intermediate",
        "Name begins with S",
        "Return customers whose Name begins with S.",
        "SELECT Name FROM Customers WHERE Name LIKE 'S%'",
        "SELECT Name FROM Customers\nWHERE Name LIKE 'S%';",
      ],
      { id: "name-begins-with-s", legacyIndex: 6 },
    ),
    Object.assign(
      [
        "Aggregate",
        "Beginner",
        "Count customers",
        "Return COUNT(*) as TotalCustomers.",
        "SELECT COUNT(*) AS TotalCustomers FROM Customers",
        "SELECT COUNT(*) AS TotalCustomers\nFROM Customers;",
      ],
      { id: "count-customers", legacyIndex: 7 },
    ),
    Object.assign(
      [
        "Aggregate",
        "Beginner",
        "Average price",
        "Return AVG(Price) as AveragePrice.",
        "SELECT AVG(Price) AS AveragePrice FROM Products",
        "SELECT AVG(Price) AS AveragePrice\nFROM Products;",
      ],
      { id: "average-price", legacyIndex: 8 },
    ),
    Object.assign(
      [
        "Aggregate",
        "Beginner",
        "Maximum price",
        "Return MAX(Price) as MaxPrice.",
        "SELECT MAX(Price) AS MaxPrice FROM Products",
        "SELECT MAX(Price) AS MaxPrice\nFROM Products;",
      ],
      { id: "maximum-price", legacyIndex: 9 },
    ),
    Object.assign(
      [
        "Aggregate",
        "Intermediate",
        "Total quantity sold",
        "Return SUM(Quantity) as TotalQuantity from OrderItems.",
        "SELECT SUM(Quantity) AS TotalQuantity FROM OrderItems",
        "SELECT SUM(Quantity) AS TotalQuantity\nFROM OrderItems;",
      ],
      { id: "total-quantity-sold", legacyIndex: 10 },
    ),
    Object.assign(
      [
        "GROUP BY",
        "Intermediate",
        "Customers per city",
        "Return City and COUNT(*) as CustomerCount, ordered by City.",
        "SELECT City,COUNT(*) AS CustomerCount FROM Customers GROUP BY City ORDER BY City",
        "SELECT City, COUNT(*) AS CustomerCount\nFROM Customers\nGROUP BY City\nORDER BY City;",
      ],
      { id: "customers-per-city", legacyIndex: 11 },
    ),
    Object.assign(
      [
        "GROUP BY",
        "Intermediate",
        "Products per category",
        "Return Category and product count as ProductCount, ordered by Category.",
        "SELECT Category,COUNT(*) AS ProductCount FROM Products GROUP BY Category ORDER BY Category",
        "SELECT Category, COUNT(*) AS ProductCount\nFROM Products\nGROUP BY Category\nORDER BY Category;",
      ],
      { id: "products-per-category", legacyIndex: 12 },
    ),
    Object.assign(
      [
        "GROUP BY",
        "Advanced",
        "Categories above average 100",
        "Return Category and AVG(Price) as AvgPrice only for categories with average price > 100, ordered by Category.",
        "SELECT Category,AVG(Price) AS AvgPrice FROM Products GROUP BY Category HAVING AVG(Price)>100 ORDER BY Category",
        "SELECT Category, AVG(Price) AS AvgPrice\nFROM Products\nGROUP BY Category\nHAVING AVG(Price) > 100\nORDER BY Category;",
      ],
      { id: "categories-above-average-100", legacyIndex: 13 },
    ),
    Object.assign(
      [
        "JOIN",
        "Intermediate",
        "Orders and customers",
        "Return OrderID and customer Name for every order, ordered by OrderID.",
        "SELECT o.OrderID,c.Name FROM Orders o JOIN Customers c ON o.CustomerID=c.CustomerID ORDER BY o.OrderID",
        "SELECT o.OrderID, c.Name\nFROM Orders o JOIN Customers c\nON o.CustomerID=c.CustomerID\nORDER BY o.OrderID;",
      ],
      { id: "orders-and-customers", legacyIndex: 14 },
    ),
    Object.assign(
      [
        "JOIN",
        "Intermediate",
        "Order product details",
        "Return OrderID, ProductName, Quantity ordered by OrderID then ProductName.",
        "SELECT oi.OrderID,p.ProductName,oi.Quantity FROM OrderItems oi JOIN Products p ON oi.ProductID=p.ProductID ORDER BY oi.OrderID,p.ProductName",
        "SELECT oi.OrderID, p.ProductName, oi.Quantity\nFROM OrderItems oi JOIN Products p\nON oi.ProductID=p.ProductID\nORDER BY oi.OrderID, p.ProductName;",
      ],
      { id: "order-product-details", legacyIndex: 15 },
    ),
    Object.assign(
      [
        "JOIN",
        "Advanced",
        "Customer order dates",
        "Return customer Name, OrderID and OrderDate ordered by OrderID.",
        "SELECT c.Name,o.OrderID,o.OrderDate FROM Customers c JOIN Orders o ON c.CustomerID=o.CustomerID ORDER BY o.OrderID",
        "SELECT c.Name, o.OrderID, o.OrderDate\nFROM Customers c JOIN Orders o\nON c.CustomerID=o.CustomerID\nORDER BY o.OrderID;",
      ],
      { id: "customer-order-dates", legacyIndex: 16 },
    ),
    Object.assign(
      [
        "JOIN",
        "Advanced",
        "Order line value",
        "Return OrderID, ProductName, and Quantity*Price as LineTotal, ordered by OrderID then ProductName.",
        "SELECT oi.OrderID,p.ProductName,oi.Quantity*p.Price AS LineTotal FROM OrderItems oi JOIN Products p ON oi.ProductID=p.ProductID ORDER BY oi.OrderID,p.ProductName",
        "SELECT oi.OrderID,p.ProductName,oi.Quantity*p.Price AS LineTotal\nFROM OrderItems oi JOIN Products p ON oi.ProductID=p.ProductID\nORDER BY oi.OrderID,p.ProductName;",
      ],
      { id: "order-line-value", legacyIndex: 17 },
    ),
    Object.assign(
      [
        "Subqueries",
        "Intermediate",
        "Above average price",
        "Return ProductName and Price for products above overall average price, ordered by Price.",
        "SELECT ProductName,Price FROM Products WHERE Price>(SELECT AVG(Price) FROM Products) ORDER BY Price",
        "SELECT ProductName, Price FROM Products\nWHERE Price > (SELECT AVG(Price) FROM Products)\nORDER BY Price;",
      ],
      { id: "above-average-price", legacyIndex: 18 },
    ),
    Object.assign(
      [
        "Subqueries",
        "Advanced",
        "Customers with orders",
        "Return Name of customers who have at least one order, ordered by Name.",
        "SELECT Name FROM Customers WHERE CustomerID IN (SELECT CustomerID FROM Orders) ORDER BY Name",
        "SELECT Name FROM Customers\nWHERE CustomerID IN (SELECT CustomerID FROM Orders)\nORDER BY Name;",
      ],
      { id: "customers-with-orders", legacyIndex: 19 },
    ),
    Object.assign(
      [
        "Subqueries",
        "Advanced",
        "Most expensive products",
        "Return ProductName and Price for product(s) matching the maximum price.",
        "SELECT ProductName,Price FROM Products WHERE Price=(SELECT MAX(Price) FROM Products)",
        "SELECT ProductName, Price FROM Products\nWHERE Price=(SELECT MAX(Price) FROM Products);",
      ],
      { id: "most-expensive-products", legacyIndex: 20 },
    ),
    Object.assign(
      [
        "DISTINCT",
        "Beginner",
        "Unique cities",
        "Return distinct City values ordered alphabetically.",
        "SELECT DISTINCT City FROM Customers ORDER BY City",
        "SELECT DISTINCT City\nFROM Customers\nORDER BY City;",
      ],
      { id: "unique-cities", legacyIndex: 21 },
    ),
    Object.assign(
      [
        "DISTINCT",
        "Beginner",
        "Unique categories",
        "Return distinct Category values ordered alphabetically.",
        "SELECT DISTINCT Category FROM Products ORDER BY Category",
        "SELECT DISTINCT Category\nFROM Products\nORDER BY Category;",
      ],
      { id: "unique-categories", legacyIndex: 22 },
    ),
    Object.assign(
      [
        "JOIN",
        "Advanced",
        "Orders per customer",
        "Return Name and number of orders as OrderCount for customers who have orders, ordered by Name.",
        "SELECT c.Name,COUNT(o.OrderID) AS OrderCount FROM Customers c JOIN Orders o ON c.CustomerID=o.CustomerID GROUP BY c.CustomerID,c.Name ORDER BY c.Name",
        "SELECT c.Name, COUNT(o.OrderID) AS OrderCount\nFROM Customers c JOIN Orders o ON c.CustomerID=o.CustomerID\nGROUP BY c.CustomerID,c.Name\nORDER BY c.Name;",
      ],
      { id: "orders-per-customer", legacyIndex: 23 },
    ),
    Object.assign(
      [
        "JOIN",
        "Advanced",
        "Revenue by product",
        "Return ProductName and SUM(Quantity*Price) as Revenue for sold products, ordered by Revenue descending.",
        "SELECT p.ProductName,SUM(oi.Quantity*p.Price) AS Revenue FROM Products p JOIN OrderItems oi ON p.ProductID=oi.ProductID GROUP BY p.ProductID,p.ProductName ORDER BY Revenue DESC",
        "SELECT p.ProductName,SUM(oi.Quantity*p.Price) AS Revenue\nFROM Products p JOIN OrderItems oi ON p.ProductID=oi.ProductID\nGROUP BY p.ProductID,p.ProductName\nORDER BY Revenue DESC;",
      ],
      { id: "revenue-by-product", legacyIndex: 24 },
    ),
    Object.assign(
      [
        "NULL/LEFT JOIN",
        "Advanced",
        "Customers without orders",
        "Return Name of customers with no orders, ordered by Name.",
        "SELECT c.Name FROM Customers c LEFT JOIN Orders o ON c.CustomerID=o.CustomerID WHERE o.OrderID IS NULL ORDER BY c.Name",
        "SELECT c.Name FROM Customers c\nLEFT JOIN Orders o ON c.CustomerID=o.CustomerID\nWHERE o.OrderID IS NULL\nORDER BY c.Name;",
      ],
      { id: "customers-without-orders", legacyIndex: 25 },
    ),
    Object.assign(
      [
        "INSERT/UPDATE",
        "Intermediate",
        "Insert customer",
        "Insert CustomerID 6, Nora, Jeddah.",
        "VERIFY_INSERT",
        "INSERT INTO Customers(CustomerID,Name,City) VALUES(6,'Nora','Jeddah');",
      ],
      { id: "insert-customer", legacyIndex: 26 },
    ),
    Object.assign(
      [
        "INSERT/UPDATE",
        "Intermediate",
        "Update price",
        "Change ProductID 2 price to 150.",
        "VERIFY_UPDATE",
        "UPDATE Products SET Price=150 WHERE ProductID=2;",
      ],
      { id: "update-price", legacyIndex: 27 },
    ),
    Object.assign(
      [
        "INSERT/UPDATE",
        "Intermediate",
        "Delete customer",
        "Delete CustomerID 5.",
        "VERIFY_DELETE",
        "DELETE FROM Customers WHERE CustomerID=5;",
      ],
      { id: "delete-customer", legacyIndex: 28 },
    ),
    Object.assign(
      [
        "JOIN",
        "Advanced",
        "Customer total spend",
        "Return Name and SUM(Quantity*Price) as TotalSpend for customers with purchases, ordered by TotalSpend descending.",
        "SELECT c.Name,SUM(oi.Quantity*p.Price) AS TotalSpend FROM Customers c JOIN Orders o ON c.CustomerID=o.CustomerID JOIN OrderItems oi ON o.OrderID=oi.OrderID JOIN Products p ON oi.ProductID=p.ProductID GROUP BY c.CustomerID,c.Name ORDER BY TotalSpend DESC",
        "SELECT c.Name,SUM(oi.Quantity*p.Price) AS TotalSpend\nFROM Customers c JOIN Orders o ON c.CustomerID=o.CustomerID\nJOIN OrderItems oi ON o.OrderID=oi.OrderID\nJOIN Products p ON oi.ProductID=p.ProductID\nGROUP BY c.CustomerID,c.Name\nORDER BY TotalSpend DESC;",
      ],
      { id: "customer-total-spend", legacyIndex: 29 },
    ),
  ],
  "web-lab": [
    Object.assign(
      [
        "Build a heading",
        "Create an H1 heading containing the text Welcome to Tamareen.",
        "<!doctype html>\n<html><head><style>body{font-family:Arial;padding:30px}</style></head><body>\n<!-- Add your H1 here -->\n</body></html>",
      ],
      { id: "build-a-heading", legacyIndex: 0 },
    ),
    Object.assign(
      [
        "Style a button",
        "Create a button and use CSS to give it padding and a border-radius.",
        "<!doctype html>\n<html>\n<head><style>\n/* Style the button */\n</style></head>\n<body>\n<button>Start Practice</button>\n</body>\n</html>",
      ],
      { id: "style-a-button", legacyIndex: 1 },
    ),
    Object.assign(
      [
        "Create a link",
        "Add a hyperlink to https://tamareen.online with the visible text Tamareen.",
        "<!doctype html>\n<html>\n<body>\n<!-- Add the link here -->\n</body>\n</html>",
      ],
      { id: "create-a-link", legacyIndex: 2 },
    ),
    Object.assign(
      [
        "JavaScript interaction",
        "Create a button that changes the paragraph text when clicked.",
        '<!doctype html>\n<html>\n<body>\n<p id="message">Ready</p>\n<button onclick="changeText()">Change text</button>\n<script>\nfunction changeText(){\n  // Change #message text here\n}\n</script>\n</body>\n</html>',
      ],
      { id: "javascript-interaction", legacyIndex: 3 },
    ),
    Object.assign(
      [
        "Responsive layout",
        "Create a CSS media query for screens up to 600px wide.",
        '<!doctype html>\n<html>\n<head><style>\n.container{display:grid;grid-template-columns:1fr 1fr}\n/* Add a mobile media query */\n</style></head>\n<body><div class="container"><div>One</div><div>Two</div></div></body>\n</html>',
      ],
      { id: "responsive-layout", legacyIndex: 4 },
    ),
  ],
  "erp-lab": [
    {
      cat: "Process Integration",
      title: "Order-to-Cash Flow",
      context: "An ERP integrates activities across functional areas.",
      q: "Which sequence best represents an integrated order-to-cash process?",
      options: [
        "Sales order → delivery → billing → payment",
        "Payment → purchase order → hiring → billing",
        "Production → recruitment → payment → delivery",
        "Billing → sales order → procurement → payroll",
      ],
      a: 0,
      explain:
        "Order-to-cash connects sales, fulfillment, billing and customer payment.",
      id: "order-to-cash-flow",
      legacyIndex: 0,
    },
    {
      cat: "Process Integration",
      title: "Procure-to-Pay Flow",
      context:
        "Procurement transactions affect purchasing, inventory and finance.",
      q: "Which sequence is most appropriate?",
      options: [
        "Purchase requisition → purchase order → goods receipt → invoice/payment",
        "Invoice → sales order → payroll → goods receipt",
        "Goods receipt → customer order → recruitment → payment",
        "Payment → requisition → billing → delivery",
      ],
      a: 0,
      explain:
        "Procure-to-pay begins with a need and links purchasing, receipt, invoice and payment.",
      id: "procure-to-pay-flow",
      legacyIndex: 1,
    },
    {
      cat: "ERP Data",
      title: "Shared Master Data",
      context: "ERP modules rely on consistent enterprise data.",
      q: "A customer's address changes. What ERP design principle best avoids inconsistent copies across departments?",
      options: [
        "Shared master data",
        "Separate spreadsheets for every unit",
        "Manual re-entry in each module",
        "Independent databases with no integration",
      ],
      a: 0,
      explain: "Shared master data supports a consistent enterprise-wide view.",
      id: "shared-master-data",
      legacyIndex: 2,
    },
    {
      cat: "ERP Data",
      title: "Transaction Impact",
      context: "One transaction can update multiple parts of an ERP.",
      q: "A goods receipt is posted for purchased inventory. Which areas are most directly affected?",
      options: [
        "Inventory and purchasing records, with possible financial impact",
        "Only employee recruitment",
        "Only marketing campaigns",
        "Only customer service notes",
      ],
      a: 0,
      explain:
        "Integrated ERP transactions propagate relevant changes across connected functional areas.",
      id: "transaction-impact",
      legacyIndex: 3,
    },
    {
      cat: "ERP Implementation",
      title: "Fit vs Customization",
      context:
        "ERP implementation requires decisions about standard processes and customization.",
      q: "A firm wants to modify every ERP screen to match its old processes. Which concern should the team evaluate most carefully?",
      options: [
        "Customization complexity and maintenance",
        "Logo color",
        "Office seating",
        "Email signature format",
      ],
      a: 0,
      explain:
        "Heavy customization can increase implementation, upgrade and maintenance complexity.",
      id: "fit-vs-customization",
      legacyIndex: 4,
    },
    {
      cat: "ERP Implementation",
      title: "Change Management",
      context: "ERP changes processes and roles, not just software.",
      q: "Users understand the system technically but resist the new cross-functional process. What should the project strengthen?",
      options: [
        "Change management and process training",
        "Database deletion",
        "More isolated spreadsheets",
        "Removing process owners",
      ],
      a: 0,
      explain:
        "ERP success depends on organizational adoption and process change as well as technology.",
      id: "change-management",
      legacyIndex: 5,
    },
    {
      cat: "Enterprise Systems",
      title: "ERP vs Siloed Systems",
      context:
        "Enterprise systems aim to coordinate information across functions.",
      q: "Which outcome most clearly demonstrates ERP integration?",
      options: [
        "Sales and inventory use the same transaction data",
        "Every department maintains unrelated customer IDs",
        "Finance receives monthly paper copies only",
        "Inventory cannot see sales demand",
      ],
      a: 0,
      explain:
        "Integration allows functions to share coordinated data and processes.",
      id: "erp-vs-siloed-systems",
      legacyIndex: 6,
    },
    {
      cat: "Enterprise Systems",
      title: "Module Connection",
      context:
        "ERP modules support different functional areas while sharing data.",
      q: "A confirmed customer order creates demand for inventory. Which connection is most relevant?",
      options: [
        "Sales and inventory/planning",
        "Payroll and recruitment only",
        "Training and benefits only",
        "Website colors and accounting",
      ],
      a: 0,
      explain:
        "Customer demand connects sales with inventory and planning activities.",
      id: "module-connection",
      legacyIndex: 7,
    },
    {
      cat: "Process Integration",
      title: "Process Bottleneck",
      context: "Cross-functional processes should be evaluated end-to-end.",
      q: "Orders are entered quickly but shipments are delayed because stock status is updated once a week. What is the integration issue?",
      options: [
        "Inventory information is not timely across the process",
        "The sales order has too many colors",
        "Payroll runs monthly",
        "The company has a website",
      ],
      a: 0,
      explain: "Integrated processes depend on timely shared information.",
      id: "process-bottleneck",
      legacyIndex: 8,
    },
    {
      cat: "ERP Implementation",
      title: "Go-Live Readiness",
      context: "ERP projects require data, process and user readiness.",
      q: "Which combination is strongest evidence of go-live readiness?",
      options: [
        "Validated data, tested processes, trained users",
        "Untested interfaces and untrained users",
        "Incomplete master data and no process owners",
        "Only a finished logo",
      ],
      a: 0,
      explain:
        "ERP readiness is multi-dimensional: data, processes, technology and people.",
      id: "go-live-readiness",
      legacyIndex: 9,
    },
  ],
  "bi-lab": [
    {
      cat: "BI Foundations",
      title: "From Data to Decision",
      context: "BI transforms data into information that supports decisions.",
      q: "A manager wants to know whether monthly sales are above target. Which output is most useful?",
      options: [
        "A KPI comparing actual sales with target",
        "A list of every raw transaction with no summary",
        "An unrelated employee directory",
        "A blank dashboard",
      ],
      a: 0,
      explain:
        "A KPI directly connects measured performance to a business target.",
      id: "from-data-to-decision",
      legacyIndex: 0,
    },
    {
      cat: "KPIs",
      title: "Choose a KPI",
      context: "KPIs should align with the decision objective.",
      q: "For monitoring customer retention, which measure is most relevant?",
      options: [
        "Customer retention/churn rate",
        "Number of database columns",
        "Screen resolution",
        "Office floor area",
      ],
      a: 0,
      explain:
        "Retention or churn directly measures whether customers remain with the business.",
      id: "choose-a-kpi",
      legacyIndex: 1,
    },
    {
      cat: "Visualization",
      title: "Trend Visualization",
      context: "Visualization choice should fit the analytical question.",
      q: "You need to show monthly revenue over two years. Which visualization is most appropriate?",
      options: [
        "Line chart",
        "Single pie chart with 24 slices",
        "Unsorted text list",
        "Gauge for every month",
      ],
      a: 0,
      explain: "A line chart is well suited to showing change over time.",
      id: "trend-visualization",
      legacyIndex: 2,
    },
    {
      cat: "Visualization",
      title: "Category Comparison",
      context: "BI dashboards often compare performance across categories.",
      q: "Which visual best supports comparing sales across six product categories?",
      options: [
        "Bar/column chart",
        "Map with no geography",
        "Long paragraph",
        "Random icons",
      ],
      a: 0,
      explain:
        "Bars make magnitude comparisons across discrete categories clear.",
      id: "category-comparison",
      legacyIndex: 3,
    },
    {
      cat: "Data Warehousing",
      title: "Historical Analysis",
      context: "Data warehouses support integrated historical analysis.",
      q: "Why might a BI team use a data warehouse instead of querying operational systems for every dashboard?",
      options: [
        "To support integrated, historical analytical workloads",
        "To eliminate all business rules",
        "To prevent any reporting",
        "To replace every source transaction",
      ],
      a: 0,
      explain:
        "Warehousing organizes integrated historical data for analytics and reporting.",
      id: "historical-analysis",
      legacyIndex: 4,
    },
    {
      cat: "Data Warehousing",
      title: "Dimension or Measure?",
      context:
        "Analytical models distinguish descriptive dimensions from numeric measures.",
      q: "In sales analysis, which is most naturally a measure?",
      options: [
        "Sales amount",
        "Customer region",
        "Product category",
        "Calendar month name",
      ],
      a: 0,
      explain:
        "Sales amount is numeric and can be aggregated; the others commonly describe dimensions.",
      id: "dimension-or-measure",
      legacyIndex: 5,
    },
    {
      cat: "Analytics",
      title: "Descriptive Analytics",
      context: "Different analytics types answer different questions.",
      q: "A dashboard summarizes what sales happened last quarter. What type of analytics is this primarily?",
      options: ["Descriptive", "Prescriptive", "Optimization only", "None"],
      a: 0,
      explain: "Descriptive analytics summarizes what happened.",
      id: "descriptive-analytics",
      legacyIndex: 6,
    },
    {
      cat: "Analytics",
      title: "Predictive Question",
      context: "Predictive analytics estimates likely future outcomes.",
      q: "Which question is predictive?",
      options: [
        "Which customers are likely to churn next month?",
        "What were total sales last month?",
        "Which policy should we choose under constraints?",
        "How many rows are in yesterday's file?",
      ],
      a: 0,
      explain: "Estimating future churn is a predictive task.",
      id: "predictive-question",
      legacyIndex: 7,
    },
    {
      cat: "Dashboards",
      title: "Executive Dashboard",
      context:
        "Dashboards should focus attention on decision-relevant information.",
      q: "An executive dashboard has 45 unrelated metrics on one screen. What improvement is most appropriate?",
      options: [
        "Prioritize a smaller set of decision-relevant KPIs",
        "Add more unrelated metrics",
        "Remove labels",
        "Use a different color for every number",
      ],
      a: 0,
      explain:
        "Effective dashboards emphasize relevant measures and reduce unnecessary cognitive load.",
      id: "executive-dashboard",
      legacyIndex: 8,
    },
    {
      cat: "Dashboards",
      title: "Drill-down",
      context: "BI can move from summary indicators to more detailed views.",
      q: "Revenue is below target. The manager clicks the KPI to inspect region and product details. What capability is being used?",
      options: [
        "Drill-down analysis",
        "Data deletion",
        "Payroll processing",
        "Source-code compilation",
      ],
      a: 0,
      explain:
        "Drill-down moves from a summary view into more detailed dimensions.",
      id: "drill-down",
      legacyIndex: 9,
    },
  ],
  "analytics-lab": [
    {
      cat: "Data Preparation",
      title: "Missing Values",
      context: "Analytics begins with understanding and preparing data.",
      q: "A numeric field has a small number of missing values. What should an analyst do first?",
      options: [
        "Assess why values are missing and choose a justified treatment",
        "Always replace them with zero",
        "Delete the entire dataset",
        "Ignore the issue without checking",
      ],
      a: 0,
      explain:
        "Missing-data treatment should follow assessment of the pattern, meaning and analytical context.",
      id: "missing-values",
      legacyIndex: 0,
    },
    {
      cat: "Data Preparation",
      title: "Train/Test Separation",
      context:
        "Predictive models should be evaluated on data not used to fit them.",
      q: "Why keep a test set separate from model training?",
      options: [
        "To estimate performance on unseen data",
        "To make the training set larger",
        "To guarantee perfect accuracy",
        "To remove the target variable",
      ],
      a: 0,
      explain:
        "A held-out test set provides a better estimate of generalization.",
      id: "train-test-separation",
      legacyIndex: 1,
    },
    {
      cat: "Descriptive Analytics",
      title: "Central Tendency",
      context: "Summary statistics describe data distributions.",
      q: "Which statistic is generally less sensitive to extreme outliers?",
      options: ["Median", "Mean", "Sum", "Range"],
      a: 0,
      explain:
        "The median depends on order and is typically more robust to extreme values.",
      id: "central-tendency",
      legacyIndex: 2,
    },
    {
      cat: "Descriptive Analytics",
      title: "Correlation",
      context: "Association does not automatically establish cause.",
      q: "Two variables have a strong correlation. What can you conclude safely?",
      options: [
        "They are associated, but correlation alone does not prove causation",
        "One definitely causes the other",
        "The data must be wrong",
        "They are identical variables",
      ],
      a: 0,
      explain:
        "Correlation quantifies association; causal conclusions require additional evidence/design.",
      id: "correlation",
      legacyIndex: 3,
    },
    {
      cat: "Predictive Analytics",
      title: "Classification Task",
      context: "Classification predicts categorical outcomes.",
      q: "Which problem is a classification problem?",
      options: [
        "Predict whether a customer will churn: yes/no",
        "Predict exact monthly revenue",
        "Calculate an average",
        "Sort rows alphabetically",
      ],
      a: 0,
      explain: "Churn yes/no is a categorical target.",
      id: "classification-task",
      legacyIndex: 4,
    },
    {
      cat: "Predictive Analytics",
      title: "Regression Task",
      context: "Regression commonly predicts continuous numeric outcomes.",
      q: "Which problem is most naturally regression?",
      options: [
        "Predict next month's sales amount",
        "Predict spam/not spam",
        "Group customers without labels",
        "Count missing cells",
      ],
      a: 0,
      explain: "Sales amount is a continuous numeric target.",
      id: "regression-task",
      legacyIndex: 5,
    },
    {
      cat: "Model Evaluation",
      title: "Confusion Matrix",
      context:
        "Classification evaluation distinguishes types of correct and incorrect predictions.",
      q: "Which evaluation tool summarizes true/false positives and true/false negatives?",
      options: [
        "Confusion matrix",
        "Histogram only",
        "ER diagram",
        "Gantt chart",
      ],
      a: 0,
      explain:
        "A confusion matrix organizes classification outcomes by actual and predicted class.",
      id: "confusion-matrix",
      legacyIndex: 6,
    },
    {
      cat: "Model Evaluation",
      title: "Overfitting",
      context: "A model can fit training data well but generalize poorly.",
      q: "Training accuracy is 99% but test accuracy is 68%. What is a likely concern?",
      options: [
        "Overfitting",
        "Perfect generalization",
        "Missing target definition is impossible",
        "The test set trained the model",
      ],
      a: 0,
      explain:
        "A large training-test performance gap is a common signal of overfitting.",
      id: "overfitting",
      legacyIndex: 7,
    },
    {
      cat: "Prescriptive Analytics",
      title: "Optimization Decision",
      context:
        "Prescriptive analytics supports choosing actions under objectives and constraints.",
      q: "A company must allocate a limited budget across projects to maximize expected return. What type of analytics is most relevant?",
      options: [
        "Prescriptive/optimization",
        "Descriptive only",
        "Data entry",
        "File compression",
      ],
      a: 0,
      explain:
        "Allocation under an objective and constraints is a prescriptive optimization problem.",
      id: "optimization-decision",
      legacyIndex: 8,
    },
    {
      cat: "Analytics Process",
      title: "Business Understanding",
      context: "Analytics should begin with a clearly framed business problem.",
      q: "Before selecting an algorithm, what should the team establish?",
      options: [
        "Business objective, target decision and success criteria",
        "A favorite algorithm regardless of problem",
        "Dashboard colors only",
        "The final result before examining data",
      ],
      a: 0,
      explain:
        "Problem framing guides data needs, method selection and evaluation.",
      id: "business-understanding",
      legacyIndex: 9,
    },
  ],
};
// Capstones combine collections, branching, arithmetic and reusable functions.
LAB_CONTENT["python-lab"].push(
  Object.assign(
    [
      "Projects",
      "Advanced",
      "Project: sales dashboard",
      'Define sales_report(rows). Each row has region, amount and status. Include only status="paid"; return a dictionary of total amount per region. Empty input returns {}.',
      'sales_report([{region:"West",amount:100,status:"paid"}]) → {"West":100}',
      "def sales_report(rows):\n    pass",
      [
        ["expr", "sales_report([])", {}],
        [
          "expr",
          'sales_report([{"region":"West","amount":100,"status":"paid"},{"region":"West","amount":30,"status":"paid"},{"region":"East","amount":20,"status":"pending"},{"region":"East","amount":40,"status":"paid"}])',
          { West: 130, East: 40 },
        ],
        [
          "expr",
          'sales_report([{"region":"North","amount":0,"status":"paid"}])',
          { North: 0 },
        ],
      ],
    ],
    { id: "project-sales-dashboard", legacyIndex: 30 },
  ),
  Object.assign(
    [
      "Projects",
      "Advanced",
      "Project: inventory planner",
      "Define reorder(items). Each item has sku, stock and target (nonnegative integers). Return a dictionary mapping only understocked SKUs to target-stock. SKUs are unique.",
      "stock 3, target 8 → order 5",
      "def reorder(items):\n    pass",
      [
        ["expr", "reorder([])", {}],
        [
          "expr",
          'reorder([{"sku":"A","stock":3,"target":8},{"sku":"B","stock":10,"target":10},{"sku":"C","stock":12,"target":9}])',
          { A: 5 },
        ],
        ["expr", 'reorder([{"sku":"D","stock":0,"target":4}])', { D: 4 }],
      ],
    ],
    { id: "project-inventory-planner", legacyIndex: 31 },
  ),
  Object.assign(
    [
      "Projects",
      "Advanced",
      "Project: customer invoice",
      'Define invoice(lines). Each line has price and quantity (nonnegative numbers). Return {"subtotal": sum(price*quantity), "discount":10% of subtotal if subtotal>=500 else 0, "total":subtotal-discount}. Round all returned values to 2 decimals.',
      "[{price:100,quantity:5}] → {subtotal:500,discount:50,total:450}",
      "def invoice(lines):\n    pass",
      [
        ["expr", "invoice([])", { subtotal: 0, discount: 0, total: 0 }],
        [
          "expr",
          'invoice([{"price":100,"quantity":5}])',
          { subtotal: 500, discount: 50, total: 450 },
        ],
        [
          "expr",
          'invoice([{"price":49.9,"quantity":10}])',
          { subtotal: 499, discount: 0, total: 499 },
        ],
        [
          "expr",
          'invoice([{"price":200,"quantity":2},{"price":80,"quantity":3}])',
          { subtotal: 640, discount: 64, total: 576 },
        ],
      ],
    ],
    { id: "project-customer-invoice", legacyIndex: 32 },
  ),
);
