const bank313=[
['What is a computer program?','A sequence of stored instructions','A physical input device','A network cable','A database table','A program is a sequence of instructions executed by a computer.'],
['Which component runs program instructions?','Central Processing Unit (CPU)','Secondary memory','Keyboard','Printer','The CPU executes program instructions.'],
['Which memory is fast, temporary, and lost on reboot?','Main memory (RAM)','Secondary memory','USB storage','Hard disk','RAM is temporary main memory.'],
['Which storage normally persists after power is removed?','Secondary memory','Main memory','CPU cache only','Keyboard buffer','Secondary storage is persistent.'],
['Which is an input device?','Keyboard','Printer','Speaker','Monitor','A keyboard sends input to the computer.'],
['Which is an output device?','Printer','Mouse','Keyboard','Touch sensor','A printer produces output.'],
['What suffix conventionally identifies a Python script?','.py','.html','.sql','.css','Python scripts conventionally use .py.'],
['What does a syntax error indicate?','The code violates Python language syntax','The CPU is too slow','The disk is full','The network is disconnected','Syntax errors mean code does not follow language grammar.'],
['Interactive Python is especially useful for what?','Short experiments and a few lines of code','Only large production systems','Database design','Image editing','Interactive mode is useful for experiments and short code.'],
['What is a Python script?','A file containing a sequence of Python statements','A CPU component','A type of RAM','A network protocol','A script stores Python statements in a file.'],
['Which program-flow type may skip steps based on a condition?','Conditional flow','Sequential flow only','Storage flow','Hardware flow','Conditional execution chooses whether steps run.'],
['Which program-flow type repeats a group of steps?','Iteration','Assignment','Compilation','Concatenation','Iteration repeats steps.'],
['Which is a valid Python variable name?','spam23','23spam','var.12','#sign','Names can contain letters, digits and underscores but cannot start with a digit.'],
['Python variable names are:','Case sensitive','Always lowercase','Case insensitive','Limited to three characters','spam, Spam and SPAM are different names.'],
['Which symbol performs assignment in Python?','=','==','!=','**','A single equals sign assigns a value.'],
['Which operator tests equality?','==','=','%','**','Double equals compares values for equality.'],
['Which operator performs exponentiation?','**','^','//','%','Python uses ** for exponentiation.'],
['Which operator gives the remainder?','%','/','**','+','The modulo operator % returns a remainder.'],
['What is the value of 23 % 5?','3','4','5','0','23 divided by 5 leaves remainder 3.'],
['What is the value of 4 ** 3?','64','12','7','16','4 to the third power is 64.'],
['In operator precedence, which is evaluated first?','Parentheses','Addition','Subtraction','Left-to-right regardless of operator','Parentheses have highest precedence here.'],
['After parentheses, which has the highest precedence?','Exponentiation','Addition','Subtraction','Assignment','Exponentiation precedes multiplication/division and addition/subtraction.'],
['What does + do when both operands are strings?','Concatenates them','Subtracts them','Converts them to integers','Compares them','For strings, + concatenates.'],
['What does type(1) report?','int','float','str','bool','1 is an integer literal.'],
['What does type(1.0) report?','float','int','str','list','1.0 is a floating-point value.'],
['What is the result of 10 / 2 in Python 3?','5.0','5','2','10','Python 3 / division produces a float.'],
['What does float(42) produce?','42.0',"'42'",'42','An error','float() converts an integer to floating point.'],
['What does input() return?','A string','Always an integer','Always a float','A Boolean','input() returns a string.'],
['To calculate with numeric user input, what is commonly required?','Convert it with int() or float()','Use print() first','Use len()','Add a comment','Numeric text from input() must be converted for arithmetic.'],
['What does # begin in Python?','A comment','A function definition','A loop','A string literal','Text after # is treated as a comment.'],
["Which operator means 'not equal'?",'!=','==','=','<=','!= tests inequality.'],
["Which operator means 'less than or equal to'?",'<=','>=','!=','==','<= tests whether the left side is no greater than the right.'],
['Do comparison operators normally change the variables they compare?','No','Yes, always','Only with strings','Only in loops','Comparisons return True/False without changing operands.'],
['What follows an if condition in Python syntax?','A colon (:)','A semicolon','A period','An equals sign','Python if headers end with a colon.'],
['What determines the scope of an if block in Python?','Indentation','Curly braces','Parentheses','File extension','Python uses indentation for blocks.'],
['What can happen if tabs and spaces are mixed inconsistently?','Indentation errors','Automatic correction','Faster execution','String conversion','Mixed tabs and spaces can cause indentation errors.'],
['What does an else block represent?','The alternative path when the if condition is false','A loop that always repeats','A function result','A comment block','else provides the other branch of a two-way decision.'],
['Which keyword supports additional conditions in a multi-way decision?','elif','loop','case','then','Python uses elif for additional branches.'],
['In an if/elif/else chain, how many matching branches execute?','At most one','Always all branches','Exactly two','None','The first matching branch is selected.'],
['What is a nested decision?','An if statement inside another conditional block','A loop inside a string','A function without parameters','A list inside a list only','Nested decisions place conditional logic inside another decision.'],
['What is the purpose of try/except?','Handle errors without immediately terminating the program','Repeat code forever','Sort a list','Define a variable','try/except provides error handling.'],
['If code in a try block succeeds, what happens to except?','It is skipped','It always executes','It becomes a loop','It deletes the result','except runs when the protected operation fails.'],
["If int('Bob') is attempted inside try, which path is expected?",'The except block','The successful path only','A for loop','A return statement','Nonnumeric text cannot be converted to int.'],
['For x=5, what is x < 10?','True','False','5','None','5 is less than 10.'],
['For x=5, what is x != 6?','True','False','6','None','5 is not equal to 6.'],
['Which keyword defines a function?','def','func','return','call','Python uses def to define functions.'],
['Which is a built-in Python function?','print()','computepay()','myfunction()','thing()','print() is provided by Python.'],
['Does defining a function automatically execute its body?','No','Yes','Only on Windows','Only with parameters','A function body executes when called.'],
['What is an argument?','A value passed into a function when it is called','A variable only in the definition','A syntax error','A loop counter','Arguments are supplied at invocation.'],
['What is a parameter?','A variable in a function definition that receives an argument','A printed result','A file extension','A comparison operator','Parameters name incoming argument values.'],
['What keyword sends a result back from a function?','return','print','break','input','return sends a result to the caller.'],
['What is a fruitful function?','A function that returns a value','A function with no name','A function that cannot be called','A comments-only function','Fruitful functions produce return values.'],
['What is a void/non-fruitful function?','A function that does not return a useful value','A function with two parameters','Only a built-in function','A function that always errors','Void functions do not return a useful result.'],
['What is a major benefit of functions?','Reuse code and reduce repetition','Increase duplicate code','Prevent parameters','Eliminate variables','Functions support store-and-reuse.'],
['How is a function normally invoked?','Function name followed by parentheses','Using # before its name','Using only def','Using square brackets around its name','Calls use the function name and parentheses.'],
["What does max('Hello world') return in the course example?",'w','H','d','o','The lecture example shows max() returning w.'],
['What does min() demonstrate in the functions lecture?','A built-in function operating on an argument','A user-defined loop','An assignment error','A dictionary lookup','min() is a built-in function.'],
['If addtwo(a,b) returns a+b, what is addtwo(3,5)?','8','35','2','15','3 + 5 = 8.'],
['Why break a long program into functions?','To organize logical chunks and improve reuse','To make every variable global','To eliminate indentation','To prevent input','Functions organize and reuse logical tasks.'],
['Why is while called an indefinite loop?','It continues until its logical condition becomes false','It always executes ten times','It only works on lists','It cannot terminate','Its number of iterations depends on its condition.'],
['What does break do inside a loop?','Ends the current loop','Skips only the current iteration','Restarts Python','Defines a function','break exits the current loop.'],
['What does continue do inside a loop?','Skips the rest of the current iteration and starts the next','Ends the loop permanently','Returns from a function','Sorts loop data','continue advances to the next iteration.'],
['Why is a for loop called a definite loop?','It iterates through a finite sequence of items','It always runs forever','It requires no sequence','It only works with numbers','for iterates through members of a sequence.'],
['How many times does for i in [5,4,3,2,1] execute its body?','5','4','6','1','There are five items.'],
['What causes the Lather/Rinse while loop with n=5 to be infinite?','n is never changed inside the loop','print() cannot be used in while','while cannot use >','n must be a string','The condition remains true because n never changes.'],
['A counter variable commonly starts at:','0','None always','100','-100','Counters typically initialize to zero.'],
['A running sum variable commonly starts at:','0','1 always','None always','The first item only','A sum accumulator typically starts at zero.'],
['How is an average commonly computed after a loop?','sum / count','count / sum','sum * count','sum + count','Average is total divided by count.'],
['What pattern uses an if statement inside a loop to select desired values?','Filtering','Concatenation','Function definition','Type conversion','Filtering tests each item against a condition.'],
['A Boolean search flag commonly starts as:','False','True always','1.5',"'found'",'The lecture initializes found=False.'],
['In [9,41,12,3,74,15], what is the largest value?','74','41','15','9','74 is the maximum.'],
['In [9,41,12,3,74,15], what is the smallest value?','3','9','12','15','3 is the minimum.'],
['Why is smallest often initialized to None?','So the first observed value can establish an initial minimum safely','Because None is smaller than every number','To force an infinite loop','To convert values to strings','None avoids assuming an unsafe numeric sentinel.'],
['Which operator is used in the lecture to check whether smallest is None?','is','=','+','%','The example uses smallest is None.'],
['What is a Python string?','A sequence of characters','A sequence of database rows','Only a numeric value','A loop type','Strings are sequences of characters.'],
['What index identifies the first character of a string?','0','1','-2','10','Python indexing starts at zero.'],
["For fruit='banana', what is fruit[1]?",'a','b','n','banana','Index 1 is the second character.'],
['What happens when a string index is beyond the end?','IndexError','The last character is returned','None is returned','The string expands','Out-of-range indexing raises IndexError.'],
["What is len('banana')?",'6','5','7','1','banana has six characters.'],
["For s='Monty Python', what does s[0:4] return?",'Mont','Monty','Python','Monty Python','The stop index is excluded.'],
['In a slice, the second index is:','Up to but not including that position','Always included','Ignored','A string value','Python slices exclude the stop position.'],
["What does 'n' in 'banana' evaluate to?",'True','False','n','None','n occurs in banana.'],
['What does find() return when a substring is not found?','-1','0','None always','An empty list','find() returns -1 for no match.'],
["For fruit='banana', what is fruit.find('na')?",'2','1','3','-1','The first na starts at index 2.'],
['What does strip() do?','Removes whitespace from both ends','Removes all internal spaces','Converts to uppercase','Splits into a list','strip removes leading and trailing whitespace.'],
["What does upper() produce from 'Hello Bob'?",'HELLO BOB','hello bob','Hello Bob','HelloBob','upper() returns an uppercase copy.'],
["What does replace('Bob','Jane') do to 'Hello Bob'?","Produces 'Hello Jane'","Produces 'Bob Hello'",'Deletes the string','Raises IndexError','replace substitutes matching text.'],
['Which brackets define a list literal?','Square brackets []','Curly braces {}','Parentheses ()','Angle brackets <>','List literals use square brackets.'],
['Are Python lists mutable?','Yes','No','Only empty lists','Only numeric lists','List elements can be changed by index.'],
['Are Python strings mutable in the same way as lists?','No','Yes','Only uppercase strings','Only numeric strings','Strings are immutable.'],
['What does append() do to a list?','Adds an element at the end','Sorts the list','Deletes the first element','Converts it to a string','append adds an item at the end.'],
['What does sort() do to a list?','Reorders its elements into sorted order','Creates a dictionary','Returns only the length','Adds a new element','sort changes the list order.'],
['What does split() normally produce from a string?','A list of strings','A dictionary','An integer','A Boolean','split returns a list of pieces.'],
["What is len([1,2,'joe',99])?",'4','3','5','99','The list contains four elements.'],
['How does a dictionary primarily look up values?','By keys','Only by numeric positions','By CSS selectors','By file offsets','Dictionaries map keys to values.'],
['Which braces are used for dictionary literals?','Curly braces {}','Square brackets []','Angle brackets <>','Parentheses ()','Dictionary literals use curly braces.'],
['What happens when a missing dictionary key is accessed with d[key]?','KeyError','IndexError','It always returns 0','It creates the key automatically','Direct missing-key lookup raises KeyError.'],
['What is the benefit of dict.get(key,0)?','It can provide 0 as a default when the key is absent','It deletes the key','It sorts the dictionary','It converts the key to a list','get can safely provide a default.'],
['Which pattern counts occurrences with a dictionary?','counts[word] = counts.get(word,0) + 1','counts = counts + word','word.append(counts)','counts.sort(word)','The get-and-increment pattern maintains counts.'],
['What does items() provide for dictionary iteration?','Key-value pairs','Only string lengths','Only sorted indexes','A single Boolean','items() exposes key-value pairs.']
];